"""
====================================================================
Agrivora Crop Recommendation API
====================================================================

This module implements the crop recommendation API used by the
Agrivora platform.

The API receives soil and environmental parameters from the
frontend application and returns suitable crop recommendations
generated by the machine learning model.

Responsibilities of this module
-------------------------------

1. Validate incoming request data
2. Transform user inputs into model-ready structures
3. Call the ML recommendation service
4. Store scan history in Firestore
5. Return structured crop recommendation results

Author: Agrivora Backend Team
====================================================================
"""

# ================================================================
# IMPORTS
# ================================================================

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from datetime import datetime

# Internal services
from app.services.recommend_service import recommend_crops
from app.utils.firestore import save_scan_history



# ================================================================
# API ROUTER INITIALIZATION
# ================================================================

"""
The router groups crop recommendation endpoints
under a dedicated API module.
"""

router = APIRouter(
    prefix="/recommendation",
    tags=["Crop Recommendation"]
)



# ================================================================
# REQUEST SCHEMA
# ================================================================

class RecommendRequest(BaseModel):
    """
    Request schema for the crop recommendation endpoint.

    Fields
    ------
    userId
        Unique user identifier

    soilType
        Soil classification selected by the user

    ph
        Soil pH value (0–14)

    temperature
        Current environmental temperature

    rainfall
        Rainfall level

    humidity
        Relative humidity percentage
    """

    userId: str = Field(
        ...,
        description="User ID making the recommendation request"
    )

    soilType: str = Field(
        ...,
        description="Selected soil type"
    )

    ph: float = Field(
        ...,
        ge=0,
        le=14,
        description="Soil pH value"
    )

    temperature: float = Field(
        ...,
        description="Temperature in Celsius"
    )

    rainfall: float = Field(
        ...,
        description="Rainfall measurement"
    )

    humidity: float = Field(
        ...,
        description="Relative humidity"
    )



# ================================================================
# SOIL DATA MAPPING
# ================================================================

"""
This mapping converts simplified soil types selected
by the user into detailed soil composition parameters
required by the machine learning model.
"""

SOIL_MAP = {

    "Sandy": {
        "sand": 70,
        "clay": 10,
        "organicCarbon": 0.5
    },

    "Clay": {
        "sand": 20,
        "clay": 60,
        "organicCarbon": 1.5
    },

    "Loamy": {
        "sand": 40,
        "clay": 30,
        "organicCarbon": 1.2
    }
}



# ================================================================
# HELPER FUNCTIONS
# ================================================================

def build_weather_summary(temp: float, rain: float, humid: float):
    """
    Build structured weather summary for ML model.

    Returns
    -------
    dict
        Weather data formatted for the prediction service
    """

    return {
        "temperature": temp,
        "rainfall": rain,
        "humidity": humid
    }



def validate_soil_type(soil_type: str):
    """
    Validate user provided soil type.

    If soil type is not recognized, raise HTTP error.
    """

    soil_summary = SOIL_MAP.get(soil_type)

    if soil_summary is None:

        raise HTTPException(
            status_code=400,
            detail="Invalid soil type provided"
        )

    return soil_summary



def store_history(user_id, soil, weather, ph, results):
    """
    Save crop recommendation results to Firestore.

    This allows users to view historical
    scan and recommendation data.
    """

    history_payload = {

        "userId": user_id,

        "soilSummary": soil,

        "weatherSummary": weather,

        "ph": ph,

        "results": results,

        "createdAt": datetime.utcnow()
    }

    save_scan_history(history_payload)



# ================================================================
# MAIN RECOMMENDATION ENDPOINT
# ================================================================

@router.post("/recommend")
def recommend(data: RecommendRequest):
    """
    Generate crop recommendations based on
    soil conditions and weather parameters.

    Steps executed:

    1. Validate soil type
    2. Construct weather summary
    3. Call ML prediction service
    4. Save scan history
    5. Return API response
    """

    print("--------------------------------------------------")
    print("Crop recommendation request received")
    print("User:", data.userId)
    print("--------------------------------------------------")



    # --------------------------------------------------------------
    # STEP 1 — Validate Soil
    # --------------------------------------------------------------

    soil_summary = validate_soil_type(data.soilType)



    # --------------------------------------------------------------
    # STEP 2 — Build Weather Summary
    # --------------------------------------------------------------

    weather_summary = build_weather_summary(
        data.temperature,
        data.rainfall,
        data.humidity
    )

    print("Soil Summary:", soil_summary)
    print("Weather Summary:", weather_summary)



    # --------------------------------------------------------------
    # STEP 3 — Run Machine Learning Prediction
    # --------------------------------------------------------------

    results, error = recommend_crops({

        "soil": soil_summary,

        "weather": weather_summary,

        "ph": data.ph

    })



    # --------------------------------------------------------------
    # STEP 4 — Handle Prediction Errors
    # --------------------------------------------------------------

    if error or results is None:

        print("Recommendation engine returned an error:", error)

        raise HTTPException(
            status_code=500,
            detail="Crop recommendation failed"
        )



    # --------------------------------------------------------------
    # STEP 5 — Save Scan History
    # --------------------------------------------------------------

    store_history(
        data.userId,
        soil_summary,
        weather_summary,
        data.ph,
        results
    )

    print("Recommendation stored successfully")



    # --------------------------------------------------------------
    # STEP 6 — API RESPONSE
    # --------------------------------------------------------------

    response_payload = {

        "success": True,

        "data": {
            "crops": results
        },

        "error": None
    }

    print("Returning API response")

    return response_payload